#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# List of local libraries



# The search paths for the included middleware
SEARCH_btsdk-audio=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wiced_btsdk/dev-kit/libraries/btsdk-audio/release-v4.9.5
SEARCH_btsdk-host-apps-bt-ble=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wiced_btsdk/tools/btsdk-host-apps-bt-ble/release-v4.9.3
SEARCH_btsdk-ota=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wiced_btsdk/dev-kit/libraries/btsdk-ota/release-v4.5.1
SEARCH_btsdk-pan=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wiced_btsdk/dev-kit/libraries/btsdk-pan/release-v3.3.0
SEARCH_btsdk-peer-apps-ble=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wiced_btsdk/tools/btsdk-peer-apps-ble/release-v3.3.0
SEARCH_btsdk-peer-apps-ota=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wiced_btsdk/tools/btsdk-peer-apps-ota/release-v3.3.0
SEARCH_TARGET_CYBT-343026-EVAL=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wiced_btsdk/dev-kit/bsp/TARGET_CYBT-343026-EVAL/release-v4.7.0
SEARCH_20706A2=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wiced_btsdk/dev-kit/baselib/20706A2/release-v4.9.5
SEARCH_btsdk-common=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wiced_btsdk/dev-kit/libraries/btsdk-common/release-v4.7.0
SEARCH_btsdk-include=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wiced_btsdk/dev-kit/btsdk-include/release-v4.9.3
SEARCH_btsdk-tools=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wiced_btsdk/dev-kit/btsdk-tools/release-v3.3.0
SEARCH_btsdk-utils=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wiced_btsdk/tools/btsdk-utils/release-v4.9.3
SEARCH_core-make=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/core-make/release-v1.9.1

# Search libraries added to build
SEARCH+=$(SEARCH_btsdk-audio)
SEARCH+=$(SEARCH_btsdk-host-apps-bt-ble)
SEARCH+=$(SEARCH_btsdk-ota)
SEARCH+=$(SEARCH_btsdk-pan)
SEARCH+=$(SEARCH_btsdk-peer-apps-ble)
SEARCH+=$(SEARCH_btsdk-peer-apps-ota)
SEARCH+=$(SEARCH_TARGET_CYBT-343026-EVAL)
SEARCH+=$(SEARCH_20706A2)
SEARCH+=$(SEARCH_btsdk-common)
SEARCH+=$(SEARCH_btsdk-include)
SEARCH+=$(SEARCH_btsdk-tools)
SEARCH+=$(SEARCH_btsdk-utils)
SEARCH+=$(SEARCH_core-make)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_BTSDK_AUDIO
COMPONENTS += MW_BTSDK_HOST_APPS_BT_BLE
COMPONENTS += MW_BTSDK_OTA
COMPONENTS += MW_BTSDK_PAN
COMPONENTS += MW_BTSDK_PEER_APPS_BLE
COMPONENTS += MW_BTSDK_PEER_APPS_OTA
COMPONENTS += MW_TARGET_CYBT_343026_EVAL
COMPONENTS += MW_20706A2
COMPONENTS += MW_BTSDK_COMMON
COMPONENTS += MW_BTSDK_INCLUDE
COMPONENTS += MW_BTSDK_TOOLS
COMPONENTS += MW_BTSDK_UTILS
COMPONENTS += MW_CORE_MAKE
